packages:
  - backend
  - frontend
  - docs

allowBuilds:
  "@whiskeysockets/baileys": true
  esbuild: true
  protobufjs: true

onlyBuiltDependencies:
  - "@whiskeysockets/baileys"
  - esbuild
  - protobufjs
