import type { ApiEndpoint } from "./types";

export const apiEndpoints: ApiEndpoint[] = [
  {
    id: "health",
    group: "system",
    method: "GET",
    path: "/health",
    auth: "public",
    title: { en: "Process health", id: "Health proses" },
    description: {
      en: "Simple HTTP liveness check. It does not indicate WhatsApp connection state.",
      id: "Pemeriksaan liveness HTTP sederhana. Endpoint ini tidak menunjukkan status koneksi WhatsApp.",
    },
    fields: [],
    liveMode: "safe",
  },
  {
    id: "ready",
    group: "system",
    method: "GET",
    path: "/ready",
    auth: "public",
    title: { en: "Application readiness", id: "Readiness aplikasi" },
    description: {
      en: "Returns the App ID and whether an API credential is configured.",
      id: "Mengembalikan App ID dan apakah credential API sudah dikonfigurasi.",
    },
    fields: [],
    liveMode: "safe",
  },
  {
    id: "app-info",
    group: "app",
    method: "GET",
    path: "/app/info",
    auth: "public",
    title: { en: "Gateway setup info", id: "Info setup gateway" },
    description: {
      en: "Inspect setup state, API-key source, and whether the current request is authenticated.",
      id: "Melihat status setup, sumber API key, dan apakah request saat ini terautentikasi.",
    },
    fields: [],
    liveMode: "safe",
  },
  {
    id: "app-bootstrap",
    group: "app",
    method: "POST",
    path: "/app/bootstrap",
    auth: "first-run",
    title: { en: "Bootstrap gateway credentials", id: "Bootstrap credential gateway" },
    description: {
      en: "Create or recover first-run browser credentials. Production requests must originate from CORS_ORIGIN.",
      id: "Membuat atau memulihkan credential browser saat first run. Di production request harus berasal dari CORS_ORIGIN.",
    },
    fields: [
      {
        key: "apiKey",
        location: "body",
        placeholder: "wa_<random-candidate>",
        label: { en: "API-key candidate", id: "Kandidat API key" },
        description: {
          en: "Optional wa_-prefixed candidate. The dashboard normally generates this value.",
          id: "Kandidat opsional berawalan wa_. Dashboard biasanya membuat nilai ini.",
        },
      },
    ],
    liveMode: "confirm",
    danger: "normal",
  },
  {
    id: "activity-list",
    group: "audit",
    method: "GET",
    path: "/activity",
    auth: "api-key",
    title: { en: "Query audit events", id: "Query audit event" },
    description: {
      en: "Read sanitized Wago/Baileys audit events with server-side filtering and cursor pagination.",
      id: "Membaca audit event Wago/Baileys yang sudah disanitasi dengan filter server-side dan cursor pagination.",
    },
    fields: [
      {
        key: "source",
        location: "query",
        input: "select",
        options: ["", "wago", "baileys"],
        label: { en: "Source", id: "Sumber" },
        description: { en: "Filter event source.", id: "Filter sumber event." },
      },
      {
        key: "category",
        location: "query",
        input: "select",
        options: ["", "system", "security", "connection", "recipient", "messaging"],
        label: { en: "Category", id: "Kategori" },
        description: { en: "Filter audit category.", id: "Filter kategori audit." },
      },
      {
        key: "level",
        location: "query",
        input: "select",
        options: ["", "info", "success", "warning", "error"],
        label: { en: "Level", id: "Level" },
        description: { en: "Filter severity level.", id: "Filter level severity." },
      },
      {
        key: "q",
        location: "query",
        placeholder: "connection",
        label: { en: "Search", id: "Pencarian" },
        description: {
          en: "Search code, title, and description.",
          id: "Cari pada code, title, dan description.",
        },
      },
      {
        key: "before",
        location: "query",
        placeholder: "<nextCursor>",
        label: { en: "Before cursor", id: "Cursor sebelum" },
        description: {
          en: "Cursor returned by the previous page.",
          id: "Cursor yang dikembalikan oleh halaman sebelumnya.",
        },
      },
      {
        key: "limit",
        location: "query",
        defaultValue: "100",
        placeholder: "100",
        label: { en: "Limit", id: "Limit" },
        description: {
          en: "Requested page size. The query layer clamps it to 1..200.",
          id: "Ukuran halaman yang diminta. Query layer membatasinya ke 1..200.",
        },
      },
    ],
    liveMode: "safe",
  },
  {
    id: "recipients-list",
    group: "recipients",
    method: "GET",
    path: "/recipients",
    auth: "api-key",
    title: { en: "List recipients", id: "Daftar recipient" },
    description: {
      en: "List persisted recipient policy records.",
      id: "Menampilkan recipient policy record yang dipersistenkan.",
    },
    fields: [],
    liveMode: "safe",
  },
  {
    id: "recipient-allow",
    group: "recipients",
    method: "POST",
    path: "/recipients/allow",
    auth: "api-key",
    title: { en: "Allow recipient", id: "Izinkan recipient" },
    description: {
      en: "Explicitly allow outbound messages to a recipient and clear a previous opt-out state.",
      id: "Secara eksplisit mengizinkan outbound ke recipient dan menghapus status opt-out sebelumnya.",
    },
    fields: [
      {
        key: "phone",
        location: "body",
        required: true,
        placeholder: "6281234567890",
        label: { en: "Phone", id: "Nomor" },
        description: {
          en: "Destination phone number. Local numbers beginning with 0 use the internal country-code default 62.",
          id: "Nomor tujuan. Nomor lokal yang diawali 0 menggunakan default country code internal 62.",
        },
      },
      {
        key: "label",
        location: "body",
        placeholder: "Demo recipient",
        label: { en: "Label", id: "Label" },
        description: { en: "Optional operator label.", id: "Label operator opsional." },
      },
    ],
    liveMode: "confirm",
    danger: "normal",
  },
  {
    id: "recipient-opt-out",
    group: "recipients",
    method: "POST",
    path: "/recipients/:phone/opt-out",
    auth: "api-key",
    title: { en: "Opt out recipient", id: "Opt-out recipient" },
    description: {
      en: "Block future outbound messages until permission is explicitly restored.",
      id: "Memblokir outbound berikutnya sampai permission dipulihkan secara eksplisit.",
    },
    fields: [
      {
        key: "phone",
        location: "path",
        required: true,
        placeholder: "6281234567890",
        label: { en: "Phone", id: "Nomor" },
        description: { en: "Recipient phone in the URL path.", id: "Nomor recipient pada URL path." },
      },
    ],
    liveMode: "confirm",
    danger: "normal",
  },
  {
    id: "whatsapp-status",
    group: "whatsapp",
    method: "GET",
    path: "/whatsapp/status",
    auth: "api-key",
    title: { en: "WhatsApp status", id: "Status WhatsApp" },
    description: {
      en: "Returns connection state, persistent account binding, and account-health availability/restriction signals.",
      id: "Mengembalikan status koneksi, binding akun persisten, serta availability/sinyal restriction account health.",
    },
    fields: [],
    liveMode: "safe",
  },
  {
    id: "whatsapp-qr",
    group: "whatsapp",
    method: "GET",
    path: "/whatsapp/qr",
    auth: "api-key",
    title: { en: "Current QR state", id: "Status QR saat ini" },
    description: {
      en: "Returns the current QR payload when pairing is active, otherwise the current connection status.",
      id: "Mengembalikan payload QR saat pairing aktif, atau status koneksi saat QR tidak tersedia.",
    },
    fields: [],
    liveMode: "safe",
  },
  {
    id: "whatsapp-qr-image",
    group: "whatsapp",
    method: "GET",
    path: "/whatsapp/qr/image",
    auth: "api-key",
    title: { en: "Current QR image", id: "Gambar QR saat ini" },
    description: {
      en: "Returns SVG when a QR exists; otherwise returns JSON describing connected/not-available state.",
      id: "Mengembalikan SVG ketika QR tersedia; jika tidak, JSON menjelaskan status connected/tidak tersedia.",
    },
    fields: [],
    liveMode: "safe",
  },
  {
    id: "whatsapp-pair",
    group: "whatsapp",
    method: "POST",
    path: "/whatsapp/pair",
    auth: "api-key",
    title: { en: "Start pairing", id: "Mulai pairing" },
    description: {
      en: "Start QR pairing for an unbound gateway. An existing bound account is preserved.",
      id: "Memulai QR pairing untuk gateway yang belum bound. Binding akun yang sudah ada dipertahankan.",
    },
    fields: [],
    liveMode: "confirm",
    danger: "normal",
  },
  {
    id: "whatsapp-rebind",
    group: "whatsapp",
    method: "POST",
    path: "/whatsapp/rebind",
    auth: "api-key",
    title: { en: "Replace WhatsApp binding", id: "Ganti binding WhatsApp" },
    description: {
      en: "Clear the previous auth/binding and start pairing a replacement account.",
      id: "Menghapus auth/binding sebelumnya lalu memulai pairing akun pengganti.",
    },
    fields: [],
    liveMode: "confirm",
    danger: "high",
  },
  {
    id: "message-send",
    group: "messages",
    method: "POST",
    path: "/messages/send",
    auth: "api-key",
    title: { en: "Send text message", id: "Kirim pesan teks" },
    description: {
      en: "Send protected outbound text after recipient and outbound-safety policy checks pass.",
      id: "Mengirim text outbound setelah recipient policy dan outbound-safety policy lolos.",
    },
    fields: [
      {
        key: "to",
        location: "body",
        required: true,
        placeholder: "6281234567890",
        label: { en: "Recipient", id: "Recipient" },
        description: { en: "Allowed destination phone number.", id: "Nomor tujuan yang sudah diizinkan." },
      },
      {
        key: "text",
        location: "body",
        required: true,
        input: "textarea",
        placeholder: "Hello from Wago",
        label: { en: "Text", id: "Pesan" },
        description: { en: "Text message content.", id: "Isi pesan teks." },
      },
      {
        key: "idempotencyKey",
        wireName: "Idempotency-Key",
        location: "header",
        defaultValue: "example-001",
        placeholder: "example-001",
        label: { en: "Idempotency key", id: "Idempotency key" },
        description: {
          en: "Recommended unique key for one logical message. The header takes precedence over the optional body field supported by the backend.",
          id: "Key unik yang direkomendasikan untuk satu pesan logis. Header diprioritaskan dari field body opsional yang juga didukung backend.",
        },
      },
    ],
    liveMode: "confirm",
    danger: "normal",
  },
  {
    id: "message-status",
    group: "messages",
    method: "GET",
    path: "/messages/:id/status",
    auth: "api-key",
    title: { en: "Message status", id: "Status pesan" },
    description: {
      en: "Read the retained in-memory status for a recent message ID.",
      id: "Membaca status in-memory yang masih disimpan untuk message ID terbaru.",
    },
    fields: [
      {
        key: "id",
        location: "path",
        required: true,
        placeholder: "<message-id>",
        label: { en: "Message ID", id: "Message ID" },
        description: {
          en: "Message ID returned by POST /messages/send.",
          id: "Message ID yang dikembalikan POST /messages/send.",
        },
      },
    ],
    liveMode: "safe",
  },
];

export function getEndpointById(id: string): ApiEndpoint | undefined {
  return apiEndpoints.find((endpoint) => endpoint.id === id);
}

export function requiresLiveConfirmation(endpoint: ApiEndpoint): boolean {
  return endpoint.method === "POST" || endpoint.liveMode === "confirm";
}
